services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  monitor:
    build:
      context: .                  # корень проекта
      dockerfile: ./cmd/monitor/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres

  bot:
    build:
      context: .                  # корень проекта
      dockerfile: ./cmd/bot/Dockerfile
    env_file:
      - .env
    depends_on:
      - monitor
      - postgres

volumes:
  pgdata: